# Dependencies
markdown:         gfm
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            George Georgarakis
tagline:          ''
description:      ''
url:              https://george-georgarakis.github.io/
baseurl:          https://george-georgarakis.github.io/

author:
  name:           
  url:            

paginate:         5

# Custom vars
version:          

github:
  repo:           
plugins:
  - jekyll-sitemap
